language: python
python:
  - "3.6"
cache: pip
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install pandoc
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install coveralls

install:
  - python setup.py install

script:
  - pytest torch_struct

env:
  global:
    # Doctr deploy key for harvardnlp/pytorch-struct
    - secure: "KEOIodS5WPxcjF5Ac73yr4vg+sAx1LRfEFXjsb9P+HNzdtmmeCRav6zyqhkLWiS8CXGo4CmamxwrOdZAefqC/94ebRTxrg/LrWS7TsyVboUDlpLjMVvnSGS8W71oVnIEcLTJXdnOAi64BaLmJlE9qu98yMunLdX8bi11Wo0+JOVSo3rMRGysoOIWNbBPnQnG5YEtJhsh+shFyqXlTow16N/nN0CIdgu4k3adq5dUginZYdGF+6LJ5GIEmQyMOJDLrcg8SbmaSwbcPDnBf80GNhOw45N4n28ftaeypPHy8QXOa85u2VbcKYFZk03c7B+3TGzuC5AR0n5RIiqfdn1/VF2USowBq6reKc7PbfoM8twp8qBrVLl8InjJTffvBWexG3jae6SdTwUAE926sWvX/Yr86Z8E2IswHxzrRiJO0HC7LDxnzKncZXi34ex7G/FbX2sfqLXBIzLD/wvQUjKBf7ieqw93u1vWitYB4bcm9KU5lDwj+dXpO2xikUn2akEl+yhSPDTOXfR5EkMzavu9AHxmIgED992Rfh1Bv9JjEm+utKCbbIEUSclxOuTMS7uIcuHNm8VJV82rHUM+r3/7MrlXhr4tJCWEoUijolsnutMwc5F/vBePmRxdnM8UGVKUp1IHB1Tw4AZL5AhsyzB7t4G+7O4C4exmV16BbGLjD+0="



matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 pep8-naming
      script: cd torch_struct/;flake8 --ignore "N801, E203, E266, E501, W503, F812, E741, N803, N802, N806" .
    - python: "3.6"
      install:
        - python setup.py install
        - pip install doctr
      script:
        - pip install -r docs/requirements.txt
        - cd docs/; make html; cd ..
        - set -e
        - doctr deploy --built-docs docs/build/html/ .
    - python: "3.6"
      script:
        - coverage run --source=torch_struct setup.py test
        - coveralls
